demo/config/routes.rb
Rails.application.routes.draw do

	devise_for :users
  
	root to: 'blogs#home'

 	resources :blogs do
 		member do
 			delete :delete_picture_attachment
 		end
 	end	
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo/app/models/blog.rb
class Blog < ApplicationRecord
	
	attr_accessor :remove_image 

	after_save :purge_image, if: :remove_image
	private def purge_image
		image.purge_later
	end
	


	has_many_attached :pictures
	has_one_attached :image	
	has_one_attached :note

	#builtin validation;
	validates :title, presence: true
	validates :caption, presence: true
	
	#custom validation for attached image
	validate :correct_image_type
	validate :correct_file_type

	#is used when the imageMagick is installed
	def thumbnail
		return self.image.variant(resize: '300x300')
	end

	def banner 
		return self.image.variant(resize: '1200x300!')
	end


	private

	def correct_image_type
		if image.attached? && !image.content_type.in?(%w(image/jpeg image/jpg image/png))
			errors.add(:image, " should have .jpg, .jpeg or .png extension" )
		elsif !image.attached? 
			errors.add(:image, 'required')
		end 
	end


	def correct_file_type
		if !note.attached? 
			errors.add(:note, 'required')
		end 
	end


end
  

demo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def username
   		return self.email.split('@')[0].capitalize
   end
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
		blogs_path(current_user)
	end

end

demo/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index] 
  
  def home

  end

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_picture_attachment
    @picture = ActiveStorage::Attachment.find(params[:id])
    @picture.purge_later
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:remove_image, :title, :caption, :image, :note, pictures: [])
    end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/blogs_helper.rb
module BlogsHelper
end

demo/app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image , "Cover Photo " %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="field">
    <%= form.label :image , "Pictures:" %>
    <%= form.file_field :pictures, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :note,  "Upload your note" %>
    <%= form.file_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<hr>

demo/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

demo/app/views/blogs/home.html.erb
<h1>Welcome back</h1>

<h3>Click the links below to connect with us </h3>

<% if current_user %>

	<h3><%= link_to "Post", blogs_path %></h3>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

<% else %>
	<%= link_to "Sign Up", new_user_registration_path  %>|
<%= link_to "Sign In", new_user_session_path %>
<% end %>

demo/app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cover Picture</th>
      <th>User</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
          <td><%= blog.title %></td>
          <td><%= image_tag(blog.image, style:'height:100px;') %></td>
          <td>
              <% activeuser = User.find(params[:id]=blog.user_id) %>
              <%= activeuser.username %>
          </td>
          <td><%= link_to  blog.note.filename  %></td>
          <td><%= link_to 'Show', blog %></td>

          <% if blog.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Post', new_blog_path %>
<hr>
<%= link_to 'Back to home', root_path %>

demo/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

demo/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<% if @blog.image.attached? %>
	<div>
		<%= image_tag(@blog.image, style:' height:300px') %>
		<%= form_with(model: @blog, local: true) do |form| %>			
			<%= form.label :remove_image %>
			<%= form.check_box :remove_image %><br>
			<%= form.submit   :remove_image %>
		<% end %>
	</div>

<% else %>
	<strong>No Cover Photo</strong>
<% end %>

<p>
  <strong>Caption:</strong>
  <%= @blog.caption %>
</p>

<% if @blog.pictures.attached? %>
	<div >
		<% @blog.pictures.each do |picture| %>
			<div style="border:1px dashed red;max-width:200px; max-height:300px;display: inline-block;">
				<%= image_tag(picture, style: 'max-width:200px;max-height:200px;') %><br>
				<%= link_to "Delete", delete_picture_attachment_blog_path(picture), method: :delete %>
			</div>
		<% end %>	
	</div>
<% end %>
<br>

<div>
	<%= link_to  @blog.note.filename  %>
	<%= link_to '(Downlod)
	', @blog.note, download: '' %>
</div>

<div> <strong>Author: </strong>
	<% id = @blog.user_id %>
	<% activeuser = User.find(params[:id]=id) %>
	<%= activeuser.username %>
</div>

<hr>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>